<?php
/**
 * Created by PhpStorm.
 * User: youxu
 * Date: 2018/2/24
 * Time: 下午4:56
 */
namespace backend\controllers;
use Yii;
use yii\web\Controller;
use backend\components\event\MailEvent;

class SendMailController extends Controller{

    const SEND_MAIL = 'send_mail';
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->on(self::SEND_MAIL,['backend\components\Mail','sendMail']);
    }
    public function actionSend(){
        $event = new MailEvent();
        $event->email = 'youxu@jhmobi.com';
        $event->subject = '事件邮件测试';
        $event->content = '邮件测试内容';
        $this->trigger(self::SEND_MAIL,$event);
    }
}