<?php
/**
 * Created by PhpStorm.
 * User: youxu
 * Date: 2018/3/6
 * Time: 上午9:37
 */

namespace backend\components\widgets\upload;

use Yii;
use yii\widgets\InputWidget;

class FileInput extends InputWidget
{
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
    }

}