<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "blog".
 *
 * @property int $id
 * @property string $content
 * @property string $title
 */
class Blog extends \yii\db\ActiveRecord
{
    public $category;
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'blog';
    }

    public function init ()
    {
        parent::init();
        $this->on(self::EVENT_BEFORE_INSERT, [$this, 'onBeforeInsert']);
        $this->on(self::EVENT_AFTER_INSERT, [$this, 'onAfterInsert']);
    }
    public function onBeforeInsert ($event)
    {
        yii::info('This is beforeInsert event.');
    }
    public function onAfterInsert ($event)
    {
        yii::info('This is alterInsert event.');
    }
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title', 'content', 'category'], 'required'],
            [['content', 'title'], 'string', 'max' => 100],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'content' => 'Content',
            'title' => 'Title',
        ];
    }
}
